sudo: required

language: go

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - curl -fsSL get.docker.com | bash

script:
  - docker build -t vterdunov/docktor:${COMMIT} .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag vterdunov/docktor:${COMMIT} vterdunov/docktor:latest;
      docker push vterdunov/docktor:${COMMIT};
      docker push vterdunov/docktor:latest;
    fi
